#数据库配置文件
#存储方式（SQLite|MySQL）
type: SQLite

#数据库信息（存储方式为SQLite的无需填写）
mysql_ip: 127.0.0.1
mysql_port: 3306
mysql_username: root
mysql_password: 123456
#数据库需要你来建
mysql_database: "chouka"
mysql_option: "useUnicode=true&characterEncoding=utf-8&useSSL=false"